name: Feature Request / 功能请求
description: Suggest an idea for this project / 为本项目提出建议
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        感谢您建议新功能！
  - type: textarea
    id: scenario
    attributes:
      label: Scenario / Context / 场景
      description: What is the problem or scenario that this feature addresses? Is your feature request related to a problem? Please describe. / 这个功能解决了什么问题或适用于什么场景？您的功能请求是否与某个问题相关？请描述。
      placeholder: I'm always frustrated when... / 我总是感到沮丧当...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Detailed Description / 具体说明
      description: Describe the solution you'd like. / 请描述您想要的解决方案。
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered / 替代方案
      description: Describe alternatives you've considered. / 请描述您考虑过的替代方案。
